### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [cmink/BrightScript.tmbundle#2]
I would like to use your grammar for BrightScript but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by pchaigno** [comment]
@cmink Did you get a chance to look into this? I'm considering using your grammar at [github/linguist](https://github.com/github/linguist) to highlight BrightScript code on GitHub.

**Comment by nbrew** [comment]
We've opted for the MIT License. Hope this works for you.

**Comment by pchaigno** [comment]
Great! Thanks!

**Comment by pchaigno** [comment]
@nbrew Your grammar is now used to highlight BrightScript code on GitHub (files and code snippets in Markdown documents)! (See github/linguist#2119 for more information.)
